version: '3.8'

services:
  # Database service
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: game_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # NestJS application service
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: db_user
      DB_PASSWORD: db_password
      DB_NAME: game_db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
